version: "3.8"
services:
    cms:
        restart: unless-stopped
        build:
            context: ./crafting-room-cms
        ports:
            - "1337:1337"
        networks:
            - app
        volumes:
            - ./crafting-room-cms/config:/opt/app/config
            - ./crafting-room-cms/yarn.lock:/opt/yarn.lock
            - ./crafting-room-cms/public/uploads:/opt/app/public/uploads
            - ./crafting-room-cms/data:/opt/app/data
    frontend:
        restart: unless-stopped
        build:
            context: ./crafting-room-frontend
            network: app
        depends_on:
            - cms
        ports:
            - "3000:3000"
        networks:
            - app
networks:
    app:
        name: app
